version: '3.5'

services:
  telegramstt:
    image: mawalla/telegram-stt
    environment:
      - ADMINNAME=@MaWalla
    volumes:
      - "/opt/telegram-tts/auth:/auth"
    networks:
      telegramstt:
        ipv4_address: 172.13.13.2
  deepspeech:
    image: mawalla/deepspeech-server
    volumes:
      - "/opt/telegram-tts/deepspeech:/opt/deepspeech"
    networks:
      telegramstt:
        ipv4_address: 172.13.9.3
networks:
  telegramstt:
    ipam:
      config:
        - subnet: 172.13.13.0/29